name: lec-24-2-dl
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pynvml
  - pytorch-gpu
  - torchvision
  - matplotlib
  - seaborn
  - pandas
  - ipykernel
  - tqdm
  - pip
  - pip:
    - ucimlrepo
